# Generated by Django 2.0 on 2018-05-11 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('dashboard', '0002_auto_20180510_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='Home.Usuario'),
            preserve_default=False,
        ),
    ]
